server.port=8761
spring.application.name=service-registry

# Explicitly define Eureka server behavior
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=true
eureka.server.wait-time-in-ms-when-sync-empty=0

# ? Fix: Explicitly define Eureka client default zone
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ? Fix: Ensure Eureka Client has valid hostname
eureka.instance.hostname=localhost
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90
