server.port=8888
spring.application.name=config-server

# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Enable Config Server
spring.cloud.config.server.git.uri=https://github.com/your-github-repo/workxlife-config.git
spring.cloud.config.server.git.clone-on-start=true
